/* ============================================================
   site-search.js  ·  WBF global site search
   ============================================================

   One search across the whole site, opened from the header.

   Sources — none of them hand-listed:
     • /assets/search-index.json   pages, generated by
                                   tools/build-search-index.pl
     • WBFData.news                the news sheet (news + calls)
     • WBFData.events              the events sheet
     • assets/documents/documents.csv   reports, guidelines, statutes
     • assets/projects/projects.csv     awarded projects

   Everything is fetched the first time the panel is opened, in
   parallel, and results re-render as each source lands. Adding a
   news item, event, document or project needs no change here; a new
   PAGE needs the index script re-run.

   Markup and styles: the button lives in _MASTER_navbar.html, the
   panel is built here on first open, the CSS is in css/site-chrome.css.
   ============================================================ */
(function () {
  'use strict';
  if (window.__wbfSearchInit) return;

  var PAGE_INDEX_URL = '/assets/search-index.json';
  var DOCS_CSV       = '/assets/documents/documents.csv';
  var PROJECTS_CSV   = '/assets/projects/projects.csv';
  var DOC_BASE       = '/assets/documents/';

  var MAX_RESULTS      = 24;
  var MAX_PER_TYPE     = 6;
  var SNIPPET_LEN      = 150;
  /* Order results are grouped in — most actionable first. */
  var TYPE_ORDER = ['Programme', 'Call', 'News', 'Event', 'Document', 'Project', 'About', 'Page'];

  var records   = [];
  var started   = false;
  var pending   = 0;
  var els       = null;
  var lastQuery = '';
  var activeIdx = -1;
  var currentResults = [];

  /* ── helpers ─────────────────────────────────────────────── */
  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  /* Lower-cased and accent-stripped, so "Kosovo*", "GEFund," and
     "gefund" all reduce to the same thing, and "Sinkovic" finds
     "Šinković". */
  var COMBINING = /[̀-ͯ]/g;
  function fold(s) {
    var v = String(s == null ? '' : s).toLowerCase();
    return v.normalize ? v.normalize('NFD').replace(COMBINING, '') : v;
  }

  function tokens(s) {
    return fold(s).replace(/[^a-z0-9\s]+/g, ' ').split(/\s+/).filter(function (t) { return t.length > 1; });
  }

  /* Levenshtein capped at 1 — enough for a single typo, and cheap
     because it bails as soon as a second difference appears. */
  function within1(a, b) {
    if (a === b) return true;
    var la = a.length, lb = b.length;
    if (Math.abs(la - lb) > 1) return false;
    var i = 0, j = 0, diff = 0;
    while (i < la && j < lb) {
      if (a.charAt(i) === b.charAt(j)) { i++; j++; continue; }
      if (++diff > 1) return false;
      if (la > lb) i++;
      else if (lb > la) j++;
      else { i++; j++; }
    }
    if (i < la || j < lb) diff++;
    return diff <= 1;
  }

  /* ── loading ─────────────────────────────────────────────── */
  function ensureDataService() {
    if (window.WBFData && window.WBFData._initialized) return Promise.resolve();
    if (window.__wbfDataServicePromise) return window.__wbfDataServicePromise;
    window.__wbfDataServicePromise = new Promise(function (resolve) {
      var s = document.createElement('script');
      s.src = '/js/data-service.js';
      s.onload = function () { resolve(); };
      s.onerror = function () { resolve(); };   /* search degrades, never blocks */
      document.head.appendChild(s);
    });
    return window.__wbfDataServicePromise;
  }

  function add(list) {
    for (var i = 0; i < list.length; i++) {
      var r = list[i];
      r._hay = fold([r.title, r.type, r.desc, (r.heads || []).join(' '), r.text].join(' '));
      r._titleFold = fold(r.title);
      records.push(r);
    }
    pending--;
    if (lastQuery) render(lastQuery);
    else if (els) setStatus();
  }

  function fail(name) {
    return function (err) {
      pending--;
      console.warn('[WBFSearch] source "' + name + '" unavailable:', err);
      if (lastQuery) render(lastQuery);
      else if (els) setStatus();
    };
  }

  function loadPages() {
    return fetch(PAGE_INDEX_URL, { cache: 'no-cache' })
      .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })
      .then(function (rows) {
        add(rows.map(function (p) {
          return { title: p.title, type: p.type, url: p.url, desc: p.desc,
                   heads: p.heads || [], text: p.text || '' };
        }));
      });
  }

  function loadNews() {
    return ensureDataService().then(function () {
      if (!window.WBFData || !window.WBFData.news) throw new Error('news feed unavailable');
      return window.WBFData.news.all();
    }).then(function (items) {
      add(items.map(function (n) {
        var isCall = /call/i.test(n.type || '');
        return {
          title: n.title,
          type: isCall ? 'Call' : 'News',
          url: '/news/?article=' + encodeURIComponent(n.id),
          desc: n.excerpt || '',
          heads: [n.programme || ''],
          text: (n.excerpt || '') + ' ' + (n.programme || ''),
          date: n.date || ''
        };
      }));
    });
  }

  function loadEvents() {
    return ensureDataService().then(function () {
      if (!window.WBFData || !window.WBFData.events) throw new Error('events feed unavailable');
      return window.WBFData.events.all();
    }).then(function (items) {
      add(items.map(function (e) {
        return {
          title: e.title,
          type: 'Event',
          url: '/events/?event=' + encodeURIComponent(e.id),
          desc: e.summary || '',
          heads: [e.city || '', e.venue || '', e.programme || ''],
          text: [e.summary, e.description, e.city, e.venue, e.programme].join(' '),
          date: e.startDate || ''
        };
      }));
    });
  }

  function loadCsv(url, mapRow) {
    return ensureDataService().then(function () {
      return fetch(url, { cache: 'no-cache' });
    }).then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.text();
    }).then(function (text) {
      var parse = window.WBFData && window.WBFData._utils && window.WBFData._utils.parseCSV;
      if (!parse) throw new Error('CSV parser unavailable');
      add(parse(text).map(mapRow).filter(Boolean));
    });
  }

  function loadDocuments() {
    return loadCsv(DOCS_CSV, function (d) {
      if (!d.title) return null;
      if (d.status && String(d.status).toLowerCase() === 'draft') return null;
      var href = d.fileUrl ? DOC_BASE + d.fileUrl : (d.externalUrl || '/wbfdocuments/');
      return {
        title: d.title,
        type: 'Document',
        url: href,
        desc: d.summary || '',
        heads: [d.category || '', d.year || ''],
        text: [d.summary, d.category, d.year, d.fileType].join(' '),
        meta: [d.fileType, d.year].filter(Boolean).join(' · ')
      };
    });
  }

  function loadProjects() {
    return loadCsv(PROJECTS_CSV, function (p) {
      if (!p.title) return null;
      return {
        title: p.title,
        type: 'Project',
        url: '/ourgrantees/?project=' + encodeURIComponent(p.id || ''),
        desc: p.shortDescription || '',
        heads: [p.programme || '', p.implementingOrganization || ''],
        text: [p.shortDescription, p.fullDescription, p.programme,
               p.implementingOrganization, p.partners, p.countries].join(' '),
        meta: [p.programme, p.startDate ? String(p.startDate).slice(0, 4) : ''].filter(Boolean).join(' · ')
      };
    });
  }

  function loadAll() {
    if (started) return;
    started = true;
    var sources = [
      ['pages',     loadPages],
      ['news',      loadNews],
      ['events',    loadEvents],
      ['documents', loadDocuments],
      ['projects',  loadProjects]
    ];
    pending = sources.length;
    sources.forEach(function (s) {
      try { s[1]().catch(fail(s[0])); }
      catch (err) { fail(s[0])(err); }
    });
  }

  /* ── scoring ─────────────────────────────────────────────── */
  /* Weighted by where a term appears: a hit in the title is worth far
     more than the same word buried in body copy, so the page ABOUT a
     thing outranks pages that merely mention it. */
  function score(rec, qTokens, qFold) {
    var s = 0, i, t;
    var strong = false;      /* matched somewhere that carries meaning */

    /* How much of the title the query accounts for. "Our Team" for
       "team" is a far better answer than a news headline that merely
       opens with the word, so the bonus scales with coverage. */
    var cover = Math.min(1, qFold.length / (rec._titleFold.length || 1));

    if (rec._titleFold === qFold) s += 220;
    else if (rec._titleFold.indexOf(qFold) === 0) s += 70 + Math.round(90 * cover);
    else if (rec._titleFold.indexOf(qFold) !== -1) s += 45 + Math.round(70 * cover);
    if (qFold.length > 2 && rec._hay.indexOf(qFold) !== -1) s += 30;

    var titleTokens = rec._titleFold.split(/[^a-z0-9]+/).filter(Boolean);
    var headFold = fold((rec.heads || []).join(' '));
    var descFold = fold(rec.desc || '');

    for (i = 0; i < qTokens.length; i++) {
      t = qTokens[i];
      var hit = false;

      for (var k = 0; k < titleTokens.length; k++) {
        if (titleTokens[k] === t)            { s += 60; hit = strong = true; break; }
        if (titleTokens[k].indexOf(t) === 0) { s += 42; hit = strong = true; break; }
        if (t.length >= 5 && within1(titleTokens[k], t)) { s += 26; hit = strong = true; break; }
      }
      if (headFold.indexOf(t) !== -1) { s += 18; hit = strong = true; }
      if (descFold.indexOf(t) !== -1) { s += 14; hit = strong = true; }
      if (rec._hay.indexOf(t) !== -1) { s += 6;  hit = true; }

      if (!hit && t.length >= 5) {
        /* Last resort: a near-miss anywhere in the record. */
        var words = rec._hay.split(/[^a-z0-9]+/);
        for (var w = 0; w < words.length; w++) {
          if (within1(words[w], t)) { s += 4; hit = true; break; }
        }
      }
      if (!hit) s -= 14;      /* a term that appears nowhere counts against */
    }

    /* Pages describing a programme or the organisation are usually the
       intended destination; a single news item rarely is. */
    if (rec.type === 'Programme' || rec.type === 'About') s += 12;
    if (rec.type === 'Call') s += 6;

    /* A record that only matches deep in its body text, term by term, is
       almost always a coincidence — every page mentions "regional" and
       "cooperation". Keep it only if the whole phrase is in there. */
    if (!strong && rec._hay.indexOf(qFold) === -1) s = Math.min(s, 10);
    return s;
  }

  function search(q) {
    var qFold = fold(q).trim();
    var qTokens = tokens(q);
    if (!qTokens.length) return [];

    var scored = [];
    for (var i = 0; i < records.length; i++) {
      var sc = score(records[i], qTokens, qFold);
      if (sc > 12) scored.push({ rec: records[i], score: sc });
    }
    scored.sort(function (a, b) {
      if (b.score !== a.score) return b.score - a.score;
      return String(a.rec.title).localeCompare(String(b.rec.title));
    });

    /* Cap each type so one large source cannot crowd out the rest. */
    var perType = {}, out = [];
    for (var j = 0; j < scored.length && out.length < MAX_RESULTS; j++) {
      var ty = scored[j].rec.type;
      perType[ty] = (perType[ty] || 0) + 1;
      if (perType[ty] > MAX_PER_TYPE) continue;
      out.push(scored[j]);
    }
    return out;
  }

  /* ── snippet ─────────────────────────────────────────────── */
  function snippet(rec, qTokens) {
    var source = rec.desc && rec.desc.length > 30 ? rec.desc : (rec.text || rec.desc || '');
    if (!source) return '';
    var hay = fold(source), at = -1, i;
    for (i = 0; i < qTokens.length && at === -1; i++) at = hay.indexOf(qTokens[i]);

    var start = 0;
    if (at > 60) {
      start = at - 60;
      var sp = source.indexOf(' ', start);
      if (sp !== -1 && sp - start < 20) start = sp + 1;
    }
    var out = source.substr(start, SNIPPET_LEN);
    if (start > 0) out = '… ' + out;
    if (start + SNIPPET_LEN < source.length) out = out.replace(/\s+\S*$/, '') + ' …';
    return out;
  }

  /* Marks matches by position rather than by substituting into the
     escaped string, so a term that happens to fall inside an HTML
     entity can never produce broken markup. */
  function highlight(text, qTokens) {
    var src = String(text == null ? '' : text);
    var hay = src.toLowerCase();
    var spans = [], i, at, from;

    for (i = 0; i < qTokens.length; i++) {
      from = 0;
      while ((at = hay.indexOf(qTokens[i], from)) !== -1) {
        spans.push([at, at + qTokens[i].length]);
        from = at + qTokens[i].length;
      }
    }
    if (!spans.length) return esc(src);

    spans.sort(function (a, b) { return a[0] - b[0] || b[1] - a[1]; });

    var out = '', cursor = 0;
    for (i = 0; i < spans.length; i++) {
      var s = spans[i][0], e = spans[i][1];
      if (e <= cursor) continue;              /* already inside a mark */
      if (s < cursor) s = cursor;             /* overlapping terms */
      out += esc(src.slice(cursor, s)) + '<mark>' + esc(src.slice(s, e)) + '</mark>';
      cursor = e;
    }
    return out + esc(src.slice(cursor));
  }

  /* ── panel ───────────────────────────────────────────────── */
  function build() {
    var wrap = document.createElement('div');
    wrap.className = 'wbf-search';
    wrap.hidden = true;
    wrap.innerHTML =
      '<div class="wbf-search-backdrop" data-close></div>' +
      '<div class="wbf-search-panel" role="dialog" aria-modal="true" aria-label="Search the Western Balkans Fund">' +
        '<div class="wbf-search-bar">' +
          '<svg class="wbf-search-bar-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="7"/><line x1="16.5" y1="16.5" x2="21" y2="21"/></svg>' +
          '<input type="search" class="wbf-search-input" autocomplete="off" spellcheck="false" ' +
                 'placeholder="Search programmes, calls, news, documents…" aria-label="Search the Western Balkans Fund" ' +
                 'role="combobox" aria-expanded="false" aria-controls="wbf-search-results" aria-autocomplete="list">' +
          '<button type="button" class="wbf-search-close" data-close aria-label="Close search">' +
            '<svg viewBox="0 0 24 24" aria-hidden="true"><line x1="6" y1="6" x2="18" y2="18"/><line x1="6" y1="18" x2="18" y2="6"/></svg>' +
          '</button>' +
        '</div>' +
        '<div class="wbf-search-body">' +
          '<p class="wbf-search-status" role="status"></p>' +
          '<ul class="wbf-search-results" id="wbf-search-results" role="listbox"></ul>' +
        '</div>' +
      '</div>';
    document.body.appendChild(wrap);

    els = {
      wrap:    wrap,
      panel:   wrap.querySelector('.wbf-search-panel'),
      input:   wrap.querySelector('.wbf-search-input'),
      results: wrap.querySelector('.wbf-search-results'),
      status:  wrap.querySelector('.wbf-search-status')
    };

    wrap.addEventListener('click', function (e) {
      if (e.target.closest('[data-close]')) { close(); return; }
    });
    els.input.addEventListener('input', function () { render(els.input.value); });
    els.input.addEventListener('keydown', onKey);
    els.results.addEventListener('mousemove', function (e) {
      var li = e.target.closest('.wbf-search-item');
      if (li) setActive(parseInt(li.dataset.i, 10));
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && !wrap.hidden) close();
    });
    return els;
  }

  function setStatus(msg) {
    if (!els) return;
    if (msg) { els.status.textContent = msg; els.status.hidden = false; return; }
    if (!els.input.value.trim()) {
      els.status.textContent = pending > 0
        ? 'Preparing the index…'
        : 'Search across programmes, calls, news, events, documents and projects.';
      els.status.hidden = false;
      return;
    }
    els.status.hidden = true;
  }

  function render(q) {
    if (!els) return;
    lastQuery = q;
    var query = String(q || '').trim();

    if (!query) {
      currentResults = [];
      els.results.innerHTML = '';
      els.input.setAttribute('aria-expanded', 'false');
      setStatus();
      return;
    }

    var qTokens = tokens(query);
    currentResults = search(query);
    activeIdx = currentResults.length ? 0 : -1;

    if (!currentResults.length) {
      els.results.innerHTML = '';
      els.input.setAttribute('aria-expanded', 'false');
      setStatus(pending > 0
        ? 'Still loading content — no matches yet for “' + query + '”.'
        : 'No results for “' + query + '”.');
      return;
    }

    setStatus();
    els.input.setAttribute('aria-expanded', 'true');

    /* Group under type headings, but order the groups by their best
       result — grouping must not bury the single most relevant hit
       under a heading the reader has to scroll past. */
    var groups = {}, best = {}, order = [];
    currentResults.forEach(function (r) {
      var t = r.rec.type;
      if (!groups[t]) { groups[t] = []; order.push(t); best[t] = r.score; }
      groups[t].push(r);
      if (r.score > best[t]) best[t] = r.score;
    });
    order.sort(function (a, b) {
      if (best[b] !== best[a]) return best[b] - best[a];
      var ia = TYPE_ORDER.indexOf(a), ib = TYPE_ORDER.indexOf(b);
      return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
    });

    var idx = 0, html = '';
    order.forEach(function (type) {
      html += '<li class="wbf-search-group" role="presentation">' + esc(type) + '</li>';
      groups[type].forEach(function (r) {
        var sn = snippet(r.rec, qTokens);
        html +=
          '<li class="wbf-search-item" role="option" data-i="' + idx + '" id="wbf-search-opt-' + idx + '" aria-selected="false">' +
            '<a href="' + esc(r.rec.url) + '">' +
              '<span class="wbf-search-title">' + highlight(r.rec.title, qTokens) + '</span>' +
              (r.rec.meta ? '<span class="wbf-search-meta">' + esc(r.rec.meta) + '</span>' : '') +
              (sn ? '<span class="wbf-search-snip">' + highlight(sn, qTokens) + '</span>' : '') +
            '</a>' +
          '</li>';
        idx++;
      });
    });
    els.results.innerHTML = html;
    setActive(0);
  }

  function setActive(i) {
    if (!els) return;
    var items = els.results.querySelectorAll('.wbf-search-item');
    if (!items.length) return;
    if (i < 0) i = items.length - 1;
    if (i >= items.length) i = 0;
    activeIdx = i;
    for (var k = 0; k < items.length; k++) {
      var on = k === i;
      items[k].classList.toggle('is-active', on);
      items[k].setAttribute('aria-selected', on ? 'true' : 'false');
      if (on) {
        els.input.setAttribute('aria-activedescendant', items[k].id);
        var r = items[k].getBoundingClientRect(), p = els.results.parentNode.getBoundingClientRect();
        if (r.bottom > p.bottom) items[k].scrollIntoView({ block: 'nearest' });
        if (r.top < p.top) items[k].scrollIntoView({ block: 'nearest' });
      }
    }
  }

  function onKey(e) {
    if (e.key === 'ArrowDown')      { e.preventDefault(); setActive(activeIdx + 1); }
    else if (e.key === 'ArrowUp')   { e.preventDefault(); setActive(activeIdx - 1); }
    else if (e.key === 'Enter') {
      var active = els.results.querySelector('.wbf-search-item.is-active a');
      if (active) { e.preventDefault(); window.location.href = active.getAttribute('href'); }
    }
  }

  var lastFocus = null;

  function open() {
    if (!els) build();
    loadAll();
    lastFocus = document.activeElement;
    els.wrap.hidden = false;
    document.body.classList.add('wbf-search-open');
    requestAnimationFrame(function () { els.wrap.classList.add('is-open'); els.input.focus(); });
    setStatus();
  }

  function close() {
    if (!els || els.wrap.hidden) return;
    els.wrap.classList.remove('is-open');
    document.body.classList.remove('wbf-search-open');
    setTimeout(function () { els.wrap.hidden = true; }, 160);
    if (lastFocus && lastFocus.focus) lastFocus.focus();
  }

  function init() {
    if (window.__wbfSearchInit) return;
    var btn = document.querySelector('.nav-search');
    if (!btn) return;                        /* navbar not injected yet */
    window.__wbfSearchInit = true;
    btn.addEventListener('click', function (e) { e.preventDefault(); open(); });

    /* "/" focuses search, the way documentation sites do — but never
       while the visitor is typing somewhere else. */
    document.addEventListener('keydown', function (e) {
      if (e.key !== '/' || e.metaKey || e.ctrlKey || e.altKey) return;
      var t = e.target;
      if (t && (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.isContentEditable)) return;
      e.preventDefault();
      open();
    });

    window.WBFSearch = { open: open, close: close };
  }

  /* The navbar arrives asynchronously on most pages. */
  if (document.querySelector('.nav-search')) init();
  else {
    var tries = 0;
    var timer = setInterval(function () {
      if (document.querySelector('.nav-search') || ++tries > 60) { clearInterval(timer); init(); }
    }, 100);
  }
})();
